const authUserErrors = {
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    INVALID_NAME: 'INVALID_NAME',
    SURNAME_TOO_SHORT: 'SURNAME_TOO_SHORT',
    SURNAME_TOO_LONG: 'SURNAME_TOO_LONG',
    INVALID_SURNAME: 'INVALID_SURNAME',
    EMAIL_NOT_VALID: 'EMAIL_NOT_VALID',
    EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
    PASSWORD_INVALID_LENGTH: 'PASSWORD_INVALID_LENGTH',
    PASSWORD_NOT_VALID: 'PASSWORD_NOT_VALID',
    CONFIRM_PASSWORD_NOT_VALID: 'CONFIRM_PASSWORD_NOT_VALID',
    CONFIRM_PASSWORD_INVALID_LENGTH: 'CONFIRM_PASSWORD_INVALID_LENGTH',
    PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
    INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
    EMAIL_NOT_REGISTRATED: 'EMAIL_NOT_REGISTRATED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ERROR_WHILE_CREATING_USER: 'ERROR_WHILE_CREATING_USER',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_USER_ID: 'INVALID_USER_ID',
    INVALID_USER_ROLE: 'INVALID_USER_ROLE',
    TOKEN_HAS_EXPIRED: 'TOKEN_HAS_EXPIRED',
    UNKNKNOWN_ERROR_WHILE_VERIFYING_TOKEN: 'UNKNKNOWN_ERROR_WHILE_VERIFYING_TOKEN',
    ADMIN_ACCESS_ONLY: 'ADMIN_ACCESS_ONLY',
    UNKNOWN_ERROR_WHILE_VERIFYING_TOKEN: 'UNKNOWN_ERROR_WHILE_VERIFYING_TOKEN',
    INVALID_TOKEN_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS: 'INVALID_TOKEN_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS',
    INVALID_CREDENTIALS_PLEASE_TRY_AGAIN_LATER_OR_CONTACT_US: 'INVALID_CREDENTIALS_PLEASE_TRY_AGAIN_LATER_OR_CONTACT_US',
    YOUR_TOKEN_HAS_EXPIRED_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS: 'YOUR_TOKEN_HAS_EXPIRED_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS',
    UNKNKNOWN_ERROR_WHILE_VERIFYING_TOKEN_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS: 'UNKNKNOWN_ERROR_WHILE_VERIFYING_TOKEN_WE_HAVE_SENT_YOU_AN_EMAIL_WITH_NEW_CREDENTIALS'
}

const commonErrors = {
    SERVER_ERROR_OCCURRED: 'SERVER_ERROR_OCCURRED'
}

const emailErrors = {
    FAILED_TO_SEND_EMAIL: 'FAILED_TO_SEND_EMAIL',
    SERVER_ERROR_WHILE_SENDING_EMAIL: 'SERVER_ERROR_WHILE_SENDING_EMAIL'
}

const errorCodes = {
    authUserErrors,
    commonErrors,
    emailErrors
}

export default errorCodes